dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
env:
  - SOLIDITY_COVERAGE=true
before_install:
  - npm install truffle
matrix:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true
before_script:
  - truffle version
script:
  - npm install
  - npm run lint
  - npm run test
